version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: print_db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: print_web
    restart: always
    depends_on:
      - db
    volumes:
      - ./secrets.json:/app/secrets.json
      - ./static:/app/static  # 1. 수정: 장고가 모은 파일을 서버 호스트로 보냄
      - ./media:/app/media   # 2. 수정: 미디어 파일 공유
      - ./log:/app/log

  nginx:
    image: nginx:latest
    container_name: print_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - ./static:/app/static  # 3. 수정: 서버 호스트의 파일을 Nginx가 읽음
      - ./media:/app/media    # 4. 수정: 서버 호스트의 미디어를 Nginx가 읽음
    depends_on:
      - web